spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL

  h2:
    console:
      enabled: true

server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
