DROP SCHEMA IF EXISTS 案件 CASCADE;
CREATE SCHEMA 案件;

CREATE TABLE 案件.案件 (
    案件名 VARCHAR(100) PRIMARY KEY,
    クライアント名 VARCHAR(100) NOT NULL,
    担当者名 VARCHAR(40) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP SCHEMA IF EXISTS 金額 CASCADE;
CREATE SCHEMA 金額;

CREATE TABLE 金額.提示金額 (
    案件名 VARCHAR(100) PRIMARY KEY REFERENCES 案件.案件(案件名),
    提示金額 int NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 金額.受注金額 (
    案件名 VARCHAR(100) PRIMARY KEY REFERENCES 案件.案件(案件名),
    受注金額 int NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP SCHEMA IF EXISTS 期間 CASCADE;
CREATE SCHEMA 期間;

CREATE TABLE 期間.案件スケジュール (
    案件名 VARCHAR(100) PRIMARY KEY REFERENCES 案件.案件(案件名),
    開始 TIMESTAMP NOT NULL,
    終了 TIMESTAMP NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP SCHEMA IF EXISTS 進捗 CASCADE;
CREATE SCHEMA 進捗;

CREATE TABLE 進捗.状態区分 (
    状態区分 VARCHAR(5) PRIMARY KEY
);

INSERT INTO 進捗.状態区分
(状態区分)
VALUES
('引き合い'),
('ヒアリング'),
('提案済み'),
('契約交渉中'),
('受注'),
('失注');

CREATE TABLE 進捗.進捗 (
    案件名 VARCHAR(100) PRIMARY KEY REFERENCES 案件.案件(案件名),
    状態 VARCHAR(5) NOT NULL REFERENCES 進捗.状態区分(状態区分),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

